"""PostgreSQL state-store planning tests.

These tests define the backend-selection and migration SQL contracts without
requiring a live PostgreSQL server. End-to-end database tests can build on this
once a test service is available.
"""

import sys
from pathlib import Path

import pytest

from hermes_cli.config import DEFAULT_CONFIG, load_config, save_config
from hermes_state import (
    POSTGRES_SCHEMA_SQL,
    SCHEMA_VERSION,
    SessionDB,
    StateDatabaseConfig,
    _PostgresCursor,
    plan_postgres_migrations,
    resolve_state_database_config,
)


def test_default_state_backend_uses_sqlite_state_db(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    monkeypatch.delenv("HERMES_STATE_DATABASE_URL", raising=False)
    monkeypatch.delenv("HERMES_STATE_POSTGRES_DSN", raising=False)

    config = resolve_state_database_config(load_config())

    assert config.backend == "sqlite"
    assert config.database_url is None
    assert config.db_path == tmp_path / "state.db"


def test_default_config_includes_state_database_settings():
    assert DEFAULT_CONFIG["sessions"]["state_backend"] == "sqlite"
    assert DEFAULT_CONFIG["sessions"]["postgres_dsn"] == ""


def test_postgres_dsn_from_config_enables_postgres_backend(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    monkeypatch.delenv("HERMES_STATE_DATABASE_URL", raising=False)
    monkeypatch.delenv("HERMES_STATE_POSTGRES_DSN", raising=False)
    cfg = load_config()
    cfg["sessions"]["state_backend"] = "postgres"
    cfg["sessions"]["postgres_dsn"] = "postgresql://hermes:secret@db/hermes"
    save_config(cfg)

    config = resolve_state_database_config(load_config())

    assert config.backend == "postgres"
    assert config.database_url == "postgresql://hermes:secret@db/hermes"


def test_postgres_dsn_env_ref_is_expanded_by_load_config(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    monkeypatch.setenv("HERMES_STATE_POSTGRES_DSN", "postgresql://env/db")
    cfg = load_config()
    cfg["sessions"]["state_backend"] = "postgres"
    cfg["sessions"]["postgres_dsn"] = "${HERMES_STATE_POSTGRES_DSN}"
    save_config(cfg)

    config = resolve_state_database_config(load_config())

    assert config.database_url == "postgresql://env/db"


def test_postgres_dsn_env_var_overrides_config_value(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    monkeypatch.setenv("HERMES_STATE_DATABASE_URL", "postgresql://override/db")
    cfg = load_config()
    cfg["sessions"]["state_backend"] = "postgres"
    cfg["sessions"]["postgres_dsn"] = "postgresql://config/db"
    save_config(cfg)

    config = resolve_state_database_config(load_config())

    assert config.database_url == "postgresql://override/db"


def test_postgres_backend_without_dsn_raises_clear_error(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    monkeypatch.delenv("HERMES_STATE_DATABASE_URL", raising=False)
    monkeypatch.delenv("HERMES_STATE_POSTGRES_DSN", raising=False)
    cfg = load_config()
    cfg["sessions"]["state_backend"] = "postgres"
    save_config(cfg)

    with pytest.raises(ValueError, match="postgres_dsn|HERMES_STATE_DATABASE_URL"):
        resolve_state_database_config(load_config())


def test_postgres_schema_sql_contains_core_tables_and_current_version():
    for table in ("schema_version", "sessions", "messages", "state_meta", "compression_locks"):
        assert f"CREATE TABLE IF NOT EXISTS {table}" in POSTGRES_SCHEMA_SQL
    assert str(SCHEMA_VERSION) in POSTGRES_SCHEMA_SQL


def test_postgres_schema_sql_avoids_sqlite_only_syntax():
    lowered = POSTGRES_SCHEMA_SQL.lower()

    assert "autoincrement" not in lowered
    assert "pragma" not in lowered
    assert "fts5" not in lowered
    assert "create virtual table" not in lowered
    assert "insert or ignore" not in lowered
    assert "generated by default as identity" in lowered
    assert "on conflict" in lowered


def test_plan_postgres_migrations_are_ordered_and_contiguous():
    migrations = plan_postgres_migrations(0)
    versions = [migration.version for migration in migrations]

    assert versions == list(range(1, SCHEMA_VERSION + 1))
    assert len(versions) == len(set(versions))


def test_plan_postgres_migrations_current_version_is_noop():
    assert plan_postgres_migrations(SCHEMA_VERSION) == []


def test_plan_postgres_migrations_refuses_future_schema_version():
    with pytest.raises(ValueError, match="newer than this Hermes"):
        plan_postgres_migrations(SCHEMA_VERSION + 1)


def test_postgres_cursor_translates_sqlite_placeholders_and_insert_ignore():
    class FakeCursor:
        description = None

        def __init__(self):
            self.calls = []

        def execute(self, sql, params=None):
            self.calls.append((sql, params))

    fake = FakeCursor()
    cursor = _PostgresCursor(fake)

    cursor.execute(
        "INSERT OR IGNORE INTO sessions (id, source) VALUES (?, ?)",
        ("s1", "cli"),
    )

    assert fake.calls == [
        (
            "INSERT INTO sessions (id, source) VALUES (%s, %s) ON CONFLICT DO NOTHING",
            ("s1", "cli"),
        )
    ]


def test_sessiondb_postgres_backend_requires_psycopg(monkeypatch):
    monkeypatch.setitem(sys.modules, "psycopg", None)

    with pytest.raises(RuntimeError, match=r"hermes-agent\[postgres\]"):
        SessionDB(
            database_config=StateDatabaseConfig(
                backend="postgres",
                db_path=Path("unused"),
                database_url="postgresql://example/db",
            )
        )


def test_export_import_preserves_session_messages_and_inactive_rows(tmp_path):
    source = SessionDB(tmp_path / "source.db")
    target = SessionDB(tmp_path / "target.db")
    try:
        source.create_session("s1", "cli", model="m", cwd="/workspace")
        first_id = source.append_message("s1", "user", "hello")
        second_id = source.append_message("s1", "assistant", "world")
        source._conn.execute("UPDATE messages SET active = 0 WHERE id = ?", (second_id,))
        source._conn.commit()

        exported = source.export_session("s1", include_inactive=True)
        target.import_session(exported)

        assert target.get_session("s1")["model"] == "m"
        imported_messages = target.get_messages("s1", include_inactive=True)
        assert [msg["id"] for msg in imported_messages] == [first_id, second_id]
        assert [msg["content"] for msg in imported_messages] == ["hello", "world"]
        assert imported_messages[1]["active"] == 0
    finally:
        source.close()
        target.close()


def test_structured_content_encoding_is_postgres_text_safe():
    encoded = SessionDB._encode_content({"parts": ["image", "text"]})

    assert "\x00" not in encoded
    assert SessionDB._decode_content(encoded) == {"parts": ["image", "text"]}
    assert SessionDB._decode_content("\x00json:{\"legacy\": true}") == {"legacy": True}


def test_structured_content_encoding_preserves_literal_prefix_strings():
    literal = '__hermes_json__:["plain", "text"]'

    encoded = SessionDB._encode_content(literal)

    assert encoded != literal
    assert SessionDB._decode_content(encoded) == literal


def test_postgres_cursor_translates_sqlite_blob_newline_literals():
    class FakeCursor:
        description = None

        def __init__(self):
            self.calls = []

        def execute(self, sql, params=None):
            self.calls.append((sql, params))

    fake = FakeCursor()
    _PostgresCursor(fake).execute("SELECT REPLACE(content, X'0A', ' '), X'0D' FROM messages")

    assert fake.calls == [("SELECT REPLACE(content, chr(10), ' '), chr(13) FROM messages", None)]


def test_search_context_helper_removes_full_content(tmp_path):
    db = SessionDB(tmp_path / "search-context.db")
    try:
        db.create_session("s1", "cli")
        db.append_message("s1", "user", "before")
        match_id = db.append_message("s1", "assistant", "secret full content")
        db.append_message("s1", "user", "after")
        matches = [{"id": match_id, "content": "secret full content", "snippet": "secret"}]

        db._add_search_context(matches)

        assert "content" not in matches[0]
        assert matches[0]["context"] == [
            {"role": "user", "content": "before"},
            {"role": "assistant", "content": "secret full content"},
            {"role": "user", "content": "after"},
        ]
    finally:
        db.close()


def test_import_sessions_orders_parents_before_children(tmp_path):
    source = SessionDB(tmp_path / "source-lineage.db")
    target = SessionDB(tmp_path / "target-lineage.db")
    try:
        source.create_session("parent", "cli")
        source.create_session("child", "cli", parent_session_id="parent")
        child = source.export_session("child")
        parent = source.export_session("parent")

        assert target.import_sessions([child, parent]) == 2

        assert target.get_session("child")["parent_session_id"] == "parent"
    finally:
        source.close()
        target.close()


def test_migrate_state_postgres_requires_dsn(tmp_path, monkeypatch):
    from argparse import Namespace

    from hermes_cli.migrate import cmd_migrate_state_postgres

    monkeypatch.delenv("HERMES_STATE_DATABASE_URL", raising=False)
    sqlite_db = SessionDB(tmp_path / "state.db")
    sqlite_db.close()

    code = cmd_migrate_state_postgres(
        Namespace(
            apply=False,
            replace=False,
            update_config=False,
            active_only=False,
            sqlite_path=str(tmp_path / "state.db"),
            dsn=None,
            dsn_env="HERMES_STATE_DATABASE_URL",
            no_backup=False,
        )
    )

    assert code == 2


def test_migrate_source_iterator_streams_active_messages(tmp_path):
    from hermes_cli.migrate import (
        _iter_source_sessions,
        _source_message_count,
        _source_session_count,
    )

    source = SessionDB(tmp_path / "stream-source.db")
    try:
        source.create_session("parent", "cli")
        source.create_session("child", "cli", parent_session_id="parent")
        source.append_message("child", "user", "active message")
        inactive_message_id = source.append_message("child", "assistant", "inactive message")
        source._conn.execute("UPDATE messages SET active = 0 WHERE id = ?", (inactive_message_id,))
        source._conn.commit()

        streamed = list(_iter_source_sessions(source, include_inactive=False))

        assert _source_session_count(source, include_inactive=False) == 2
        assert _source_message_count(source, include_inactive=False) == 1
        assert [session["id"] for session in streamed] == ["parent", "child"]
        assert streamed[1]["parent_session_id"] == "parent"
        assert [message["content"] for message in streamed[1]["messages"]] == ["active message"]
    finally:
        source.close()


def test_redact_dsn_hides_url_passwords():
    from hermes_cli.migrate import _redact_dsn

    redacted = _redact_dsn(
        "postgresql://user:password123@example/db?sslpassword=cert-secret&connect_timeout=5"
    )

    assert "password123" not in redacted
    assert "cert-secret" not in redacted
    assert redacted == "postgresql://user:***@example/db?sslpassword=%2A%2A%2A&connect_timeout=5"


def test_redact_dsn_hides_keyword_passwords():
    from hermes_cli.migrate import _redact_dsn

    redacted = _redact_dsn(
        "host=db.example dbname=hermes user=hermes password='p w' passfile=/tmp/pgpass"
    )

    assert "p w" not in redacted
    assert "/tmp/pgpass" not in redacted
    assert redacted == "host=db.example dbname=hermes user=hermes password=*** passfile=***"


def test_redact_dsn_hides_escaped_keyword_passwords():
    from hermes_cli.migrate import _redact_dsn

    redacted = _redact_dsn(r"host=db password='abc\'def' user=hermes")

    assert "abc" not in redacted
    assert "def" not in redacted
    assert redacted == "host=db password=*** user=hermes"
